/**
 * @file ServerError.java
 * @author Michal Majer
 * Faculty of Information Technology
 * Brno University of Technology
 * xmajer21@stud.fit.vutbr.cz
 * @brief Server error response generated by endpoint handlers.
 * @date 18 Feb     2024 16:00 (created)
 * @section Licence
 * This file is part of the Superscalar simulator app
 * <p>
 * Copyright (C) 2023 Michal Majer
 * <p>
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * <p>
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * <p>
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.gradle.superscalarsim.server;

/**
 * @brief Server error response generated by endpoint handlers.
 * @details This error is serialized and sent to the client in case of an error.
 * This error can be generated as a response to invalid requests (e.g. missing fields, values out of permitted range, etc.).
 */
public record ServerError(String field, String message, Object extra)
{
  public ServerError(String field, String message)
  {
    this(field, message, null);
  }
  
  /**
   * @return A general, human readable error message
   */
  public String message()
  {
    return message;
  }
  
  /**
   * @return Additional information about the error. Could be a list of errors, a stack trace, etc.
   */
  public Object extra()
  {
    return extra;
  }
  
  /**
   * @return The field that caused the error. Can be null if the error is not field-specific.
   */
  public String field()
  {
    return field;
  }
}
