# Author: Michal Majer (xmajer21, misa@majer.cz)
# Date: 2023-11-01

# This file defines the CI/CD pipeline for the project.
# It is used by GitLab to run the pipeline.
#
# It defines two tags:
# - riscvsim: Can be ran in docker runner
# - docker-deploy: Can be ran in shell runner. This runner has access to docker-compose and creates the deployment
#
# There are two stages: test and deploy

default:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - docker info

# Source: https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#use-docker-in-docker
variables:
  DOCKER_TLS_CERTDIR: "/certs"
