
# Frontend website

build_frontend:
  stage: build
  image: node:18-alpine
  script:
    - cd Sources/frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - Sources/frontend/node_modules/
      - Sources/frontend/.next/

# Run Tests
test_frontend:
  stage: test
  image: node:18-alpine
  needs:
    - job: build_frontend
      artifacts: true
  script:
    - cd Sources/frontend
    - npm run test

# Deploy the app
# Runs on commit to development branch

deploy_development:
  stage: deploy
  script:
    - cd Sources
    - sudo ./run_container.sh
  environment:
    name: development-env
    url: https://sc-nas.fit.vutbr.cz:3120/
  # Only deploy on development branch
  rules:
    - if: '$CI_COMMIT_BRANCH == "development"'
      when: always

# Backend simulator

build_backend:
  stage: build
  image: gradle:8.3.0-jdk17
  script:
    - cd Sources/simulator
    - ./gradlew assemble

test_backend:
  stage: test
  image: gradle:8.3.0-jdk17
  script:
    - cd Sources/simulator
    - ./gradlew test
  allow_failure: true
