name: riscvsim
version: "2.3"
services:
  web:
    extends:
      file: docker-compose.http.yml
      service: web

  gateway:
    extends:
      file: docker-compose.http.yml
      service: gateway
    volumes:
      # The HTTPS compose is reliant on the SSL configuration.
      # Therefore, run it from Sources/
      - ./proxy/ssl.conf:/etc/nginx/ssl.conf:ro
      - ./proxy/certs:/etc/nginx/certs:ro

  simserver:
    extends:
      file: docker-compose.http.yml
      service: simserver
