name: riscvsim
version: "2.3"
services:
  web:
    image: majeris/riscv-sim-frontend:latest
    build:
      context: ./frontend
      target: runner
      args:
        DOCKER_BUILDKIT: 1
    environment:
      - NODE_ENV=production
    ports:
      - 3100:3000
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - simserver
    links:
      - simserver

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "3120:3120"
      - "3121:3121"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/certs:/etc/nginx/certs:ro
    depends_on:
      - web

  simserver:
    image: majeris/riscv-sim-backend:latest
    build:
      context: ./simulator
      target: runner
    ports:
      - 8120:8000
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"
