name: riscvsim

version: "2.3"
services:
  web:
    build:
      context: ./frontend
      target: runner
      args:
        DOCKER_BUILDKIT: 1
    environment:
      - NODE_ENV=production
    ports:
      - 3120:3000
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - simserver
    links:
      - simserver # The web server uses port 8000 to communicate with the server, 8120 is exposed to the host
  simserver:
    build:
      context: ./simulator
      target: runner
    ports:
      - 8120:8000
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"
