name: Release Containers on Docker Hub

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract release version
        run: echo "RELEASE_VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - name: Build frontend Docker image
        run: |
          nix build .#frontend-docker

      - name: Load Docker image
        run: docker load < result

      - name: Tag Docker image n.1
        run: |
          docker image tag riscv-sim-frontend ${{ secrets.DOCKER_USERNAME }}/riscv-sim-frontend:$RELEASE_VERSION

      - name: Tag Docker image n.2
        run: |
          docker image tag riscv-sim-frontend ${{ secrets.DOCKER_USERNAME }}/riscv-sim-frontend:latest

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/riscv-sim-frontend:$RELEASE_VERSION

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/riscv-sim-frontend:latest

  generate_release_notes:
    needs: release
    runs-on: ubuntu-latest

    steps:
      - name: Generate release notes
        uses: release-drafter/release-drafter@v5
        with:
          config-name: 'release-drafter.yml'
