name: Test Backend

# On every pull_request push and push to master and development
on:
  push:
    branches:
      - master
      - development
  pull_request:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Sources/simulator
    steps:
      - uses: actions/checkout@v4

      # Building the container tests it
      - name: Build Container
        run: docker build -t simulator .

