name: Test Frontend

# On every pull_request push and push to master and development
on:
  push:
    branches:
      - master
      - development
  pull_request:

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Sources/frontend
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Check formatting
        run: bun format:check

  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Sources/frontend
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Sources/frontend
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Test
        run: bun test
