name: Test Backend

# On every pull_request push and push to master and development
on:
  push:
    branches:
      - master
      - development
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Sources/simulator
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify

  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Sources/simulator
    steps:
      - uses: actions/checkout@v4

      # Building it tests it
      - name: Build Container
        run: docker build -t simulator .

